services:
  - type: web
    name: hexplora
    runtime: node
    buildCommand: npm install --include=dev && cd client && npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
